# -*- coding: utf-8 -*-
"""train_and_save.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW0AW62GLmuZeW2eWcJzEvLFTLMyWN39
"""

import pandas as pd
import joblib
import sklearn
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

print("Using sklearn version:", sklearn.__version__)

df = pd.read_csv("diabetes.csv")

target = "Outcome" if "Outcome" in df.columns else df.columns[-1]
X = df.drop(columns=[target])
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipe.fit(X_train, y_train)
joblib.dump(pipe, "logreg_pipeline.joblib")

print("✅ Saved new compatible model: logreg_pipeline.joblib")
print("Features used:", list(X.columns))

